/**
 * @risqbase-inc/ui-components-mcp — server core (v4.4 Workstream C).
 *
 * Transport-agnostic: stdio.mjs and http.mjs are thin wrappers around
 * `createServer()` (D-101 — one shared implementation). Read-only by
 * design (D-102): components, tokens, recipes, lifecycle, a11y contracts,
 * usage rules, Layer-3 showcase pointers. No codegen, no write tools.
 *
 * Data source: the generated agent registry (§C4 single source of truth —
 * the same artefact the docs site and llms.txt generator consume). The
 * published package bundles a snapshot (registry.json, regenerated by
 * `npm run build:agent-surface` and freshness-gated by scanner rule R14);
 * when running from the monorepo, the live public/agent/registry.json
 * wins so dev sessions see current data.
 *
 * Zero runtime dependencies on purpose: the MCP wire format is
 * newline-delimited JSON-RPC 2.0; ~100 lines of transport beats a
 * dependency tree in a package whose whole job is answering questions
 * about a design system.
 */

import { readFileSync, existsSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

// `new URL(…, import.meta.url)` keeps both candidates statically traceable
// by bundlers' file tracing (Vercel NFT), so the serverless wrapper ships
// the registry without extra config.
const CANDIDATES = [
  new URL('../public/agent/registry.json', import.meta.url), // monorepo dev
  new URL('./registry.json', import.meta.url), // published bundle
]

export function loadRegistry() {
  for (const url of CANDIDATES) {
    const file = fileURLToPath(url)
    if (existsSync(file)) return JSON.parse(readFileSync(file, 'utf8'))
  }
  throw new Error('ui-components-mcp: no registry.json found (run `npm run build:agent-surface`)')
}

const PROTOCOL_VERSION = '2025-06-18'

/* ── tool definitions (§C2 contract) ─────────────────────────────────── */

const str = (description) => ({ type: 'string', description })

export const TOOLS = [
  {
    name: 'list_components',
    description:
      'List design-system components. Filter by domain (core | ai | data-viz | marketing | primitives), layer (1 | 2) or promotion state (beta | stable | deprecated). Returns name, domain, layer, state and a one-line description.',
    inputSchema: {
      type: 'object',
      properties: { domain: str('Filter by domain'), layer: { type: 'number', description: 'Filter by layer (1 or 2)' }, state: str('Filter by promotion state') },
    },
  },
  {
    name: 'get_component',
    description:
      'Full contract for one component: API (props + types), token chain, accessibility contract, composes-with, canonical import, promotion state.',
    inputSchema: { type: 'object', properties: { name: str('Component name, e.g. "CitationChip"') }, required: ['name'] },
  },
  {
    name: 'list_tokens',
    description: 'List design tokens. Filter by tier (primitive | semantic | component) and/or group (e.g. "color.iris", "color.band", "shadow").',
    inputSchema: { type: 'object', properties: { tier: str('Filter by tier'), group: str('Dotted-path prefix filter') } },
  },
  {
    name: 'get_token',
    description:
      'One token in full: resolution chain primitive→semantic→component, light + dark resolved values, CSS variable, contrastPair, deprecation.',
    inputSchema: { type: 'object', properties: { path: str('Dotted token path, e.g. "color.iris.accent"') }, required: ['path'] },
  },
  {
    name: 'list_recipes',
    description: 'List §20 composition recipes: id, layer composition, use case.',
    inputSchema: { type: 'object', properties: {} },
  },
  {
    name: 'get_recipe',
    description: 'One recipe in full (v4.1 §20 schema): trigger, data shape, composed_of, layout, states, voice examples, anti-patterns.',
    inputSchema: { type: 'object', properties: { id: str('Recipe id, e.g. "motion-preference"') }, required: ['id'] },
  },
  {
    name: 'get_lifecycle',
    description: 'Promotion lifecycle: per-component state (private → beta → stable → deprecated), criteria notes, promotion-log rows. Pass component to filter.',
    inputSchema: { type: 'object', properties: { component: str('Optional component name') } },
  },
  {
    name: 'get_usage_rules',
    description: 'Scanner rules R1–R14 as machine-readable constraints: id, description, severity, what to do instead.',
    inputSchema: { type: 'object', properties: { consumer: str('Optional consumer hint (e.g. "ralia", "marketing") — informational') } },
  },
  {
    name: 'list_showcase',
    description: 'Layer-3 product-showcase entries. Every entry is consumable: false, license: "RALIA-private" — documented for understanding, NOT for reuse.',
    inputSchema: { type: 'object', properties: {} },
  },
  {
    name: 'get_showcase',
    description: 'One Layer-3 showcase entry: composition data (which Layer 1/2 primitives + configuration), the consumable/license flags, showcase URL, and what to build instead.',
    inputSchema: { type: 'object', properties: { id: str('Showcase id, e.g. "risk-gauge-configuration"') }, required: ['id'] },
  },
  {
    name: 'search',
    description: 'Ranked search across components, tokens, recipes, showcase entries and usage rules.',
    inputSchema: { type: 'object', properties: { query: str('Search query') }, required: ['query'] },
  },
]

/* ── handlers ────────────────────────────────────────────────────────── */

function componentSummary(c) {
  return { name: c.name, domain: c.domain, layer: c.layer, state: c.state, exports: c.exports, description: c.description }
}

function searchCorpus(registry) {
  const docs = []
  for (const c of registry.components) {
    docs.push({
      kind: 'component',
      id: c.name,
      // Secondary exports (e.g. BandBadge inside Badge/) rank like ids so
      // "build a risk band chip" surfaces Badge/BandBadge, not a near-miss.
      aliases: (c.exports || []).filter((e) => e !== c.name),
      ref: componentSummary(c),
      text: [c.name, c.domain, c.description, c.tokensDoc, c.accessibilityDoc, JSON.stringify(c.api)].join(' '),
    })
  }
  for (const t of registry.tokens) {
    docs.push({ kind: 'token', id: t.path, ref: { path: t.path, tier: t.tier, type: t.type, description: t.description }, text: [t.path, t.cssVariable, t.description, t.tier].join(' ') })
  }
  for (const r of registry.recipes) docs.push({ kind: 'recipe', id: r.id, ref: { id: r.id, use_case: r.use_case }, text: JSON.stringify(r) })
  for (const s of registry.showcase) {
    docs.push({ kind: 'showcase', id: s.id, ref: { id: s.id, title: s.title, consumable: false, license: 'RALIA-private' }, text: JSON.stringify(s) })
  }
  for (const r of registry.usageRules) docs.push({ kind: 'rule', id: r.id, ref: r, text: JSON.stringify(r) })
  return docs
}

export function createServer(registry = loadRegistry()) {
  const meta = () => ({ spec: registry.spec, package: registry.package, generatedAt: new Date().toISOString() })

  const handlers = {
    list_components({ domain, layer, state } = {}) {
      let list = registry.components
      if (domain) list = list.filter((c) => c.domain === domain)
      if (layer !== undefined) list = list.filter((c) => c.layer === Number(layer))
      if (state) list = list.filter((c) => c.state === state)
      return { components: list.map(componentSummary) }
    },
    get_component({ name } = {}) {
      const c = registry.components.find((x) => x.name === name || x.slug === name)
      if (!c) throw new ToolError(`Unknown component "${name}". Use list_components.`)
      return {
        ...componentSummary(c),
        stateNote: c.stateNote,
        import: c.import,
        api: c.api,
        tokenChain: c.tokensDoc,
        accessibilityContract: c.accessibilityDoc,
        composesWith: c.composesWith,
        storybook: c.storybook,
        canonicalSnippet: c.import,
      }
    },
    list_tokens({ tier, group } = {}) {
      let list = registry.tokens
      if (tier) list = list.filter((t) => t.tier === tier)
      if (group) list = list.filter((t) => t.path === group || t.path.startsWith(group.endsWith('.') ? group : group + '.'))
      return { tokens: list.map((t) => ({ path: t.path, type: t.type, tier: t.tier, description: t.description, deprecated: t.deprecated })) }
    },
    get_token({ path: tokenPath } = {}) {
      const t = registry.tokens.find((x) => x.path === tokenPath || x.cssVariable === tokenPath)
      if (!t) throw new ToolError(`Unknown token "${tokenPath}". Use list_tokens.`)
      return { ...t }
    },
    list_recipes() {
      return { recipes: registry.recipes.map((r) => ({ id: r.id, layer_composition: r.layer_composition, use_case: r.use_case })) }
    },
    get_recipe({ id } = {}) {
      const r = registry.recipes.find((x) => x.id === id)
      if (!r) throw new ToolError(`Unknown recipe "${id}". Use list_recipes.`)
      return { ...r }
    },
    get_lifecycle({ component } = {}) {
      if (component) {
        const c = registry.components.find((x) => x.name === component)
        if (!c) throw new ToolError(`Unknown component "${component}".`)
        return {
          component,
          state: c.state,
          note: c.stateNote,
          promotionLog: registry.lifecycle.promotionLog.filter((row) => row.component === component),
        }
      }
      return { states: registry.lifecycle.states, promotionLog: registry.lifecycle.promotionLog }
    },
    get_usage_rules({ consumer } = {}) {
      return { consumer: consumer ?? null, rules: registry.usageRules }
    },
    list_showcase() {
      return {
        notice: 'Layer-3 entries are RALIA-private and NOT consumable. Build from the Layer 1/2 primitives they compose.',
        showcase: registry.showcase.map((s) => ({ id: s.id, title: s.title, consumable: false, license: 'RALIA-private', summary: s.summary })),
      }
    },
    get_showcase({ id } = {}) {
      const s = registry.showcase.find((x) => x.id === id)
      if (!s) throw new ToolError(`Unknown showcase entry "${id}". Use list_showcase.`)
      return { ...s, consumable: false, license: 'RALIA-private' }
    },
    search({ query } = {}) {
      if (!query || !String(query).trim()) throw new ToolError('search requires a non-empty query')
      const terms = String(query).toLowerCase().split(/\s+/).filter(Boolean)
      const hits = searchCorpus(registry)
        .map((d) => {
          const text = d.text.toLowerCase()
          const ids = [d.id, ...(d.aliases || [])].map((x) => x.toLowerCase())
          let score = 0
          for (const term of terms) {
            const best = Math.max(...ids.map((idLower) => (idLower === term ? 10 : idLower.includes(term) ? 5 : 0)))
            score += best
            if (text.includes(term)) score += 1
          }
          // Layer-3 showcase entries are documented-not-consumable (D-104):
          // for "what do I build with" queries the consumable primitives
          // must outrank them, so they carry a rank penalty (still listed).
          if (d.kind === 'showcase') score *= 0.5
          return { ...d, score }
        })
        .filter((d) => d.score > 0)
        .sort((a, b) => b.score - a.score || a.id.localeCompare(b.id))
        .slice(0, 20)
      return { query, hits: hits.map((h) => ({ kind: h.kind, id: h.id, score: h.score, ...h.ref })) }
    },
  }

  class ToolError extends Error {}

  function callTool(name, args) {
    const handler = handlers[name]
    if (!handler) return { isError: true, content: [{ type: 'text', text: `Unknown tool: ${name}` }] }
    try {
      const result = { ...handler(args ?? {}), _meta: meta() }
      return { content: [{ type: 'text', text: JSON.stringify(result, null, 2) }] }
    } catch (err) {
      if (err instanceof ToolError) return { isError: true, content: [{ type: 'text', text: err.message }] }
      throw err
    }
  }

  /** Handle one JSON-RPC request object; returns a response object or null (notification). */
  function handleMessage(msg) {
    if (!msg || msg.jsonrpc !== '2.0') return errorResponse(msg?.id ?? null, -32600, 'Invalid request')
    const { id, method, params } = msg
    const isNotification = id === undefined
    try {
      let result
      switch (method) {
        case 'initialize':
          result = {
            protocolVersion: typeof params?.protocolVersion === 'string' ? params.protocolVersion : PROTOCOL_VERSION,
            capabilities: { tools: {} },
            serverInfo: { name: 'risqbase-ui-components', version: registry.package },
            instructions:
              'Read-only access to the RisqBase Design System: components, tokens (light+dark), recipes, lifecycle, a11y contracts, scanner rules, and Layer-3 showcase entries (which are RALIA-private and not consumable). Prefer existing primitives and semantic tokens over custom builds; run search first when unsure.',
          }
          break
        case 'ping':
          result = {}
          break
        case 'tools/list':
          result = { tools: TOOLS }
          break
        case 'tools/call':
          result = callTool(params?.name, params?.arguments)
          break
        default:
          if (isNotification) return null // notifications/initialized etc.
          return errorResponse(id, -32601, `Method not found: ${method}`)
      }
      if (isNotification) return null
      return { jsonrpc: '2.0', id, result }
    } catch (err) {
      if (isNotification) return null
      return errorResponse(id, -32603, `Internal error: ${err.message}`)
    }
  }

  return { handleMessage, callTool, registry }
}

function errorResponse(id, code, message) {
  return { jsonrpc: '2.0', id, error: { code, message } }
}
