// Tests for the README generator. Runs against the REAL repo sources (no
// mocks) — the generator's whole job is to reflect actual package state, so
// the test asserts against that state via node:test + node:assert.
//
//   node --test tools/readme-build/

import { test } from 'node:test'
import assert from 'node:assert/strict'

import { collect, renderSections, inject, generate } from './index.mjs'

test('collect() reads real package state', () => {
  const d = collect()
  assert.match(d.version, /^\d+\.\d+\.\d+/, 'version is semver')
  assert.match(d.specVersion, /^\d+\.\d+/, 'spec version derived from docs/design-system/v*')
  assert.ok(d.componentCount > 5, 'more than the original five core components are shipped')
  assert.ok(d.byDomain.core.includes('Button'), 'core exposes Button')
  assert.ok(d.byDomain.ai.includes('CitationChip'), 'ai domain is populated, not "reserved"')
  assert.ok(d.byDomain['data-viz'].length > 0, 'data-viz domain is populated')
  assert.ok(d.exportSubpaths.includes('core') && d.exportSubpaths.includes('ai'), 'subpath exports present')
  assert.ok(d.tokenCount > 0, 'token count derived from source')
})

test('renderSections() reflects shipped reality, not stale claims', () => {
  const s = renderSections(collect())
  assert.match(s.status, /design\.risqbase\.com/, 'status links the live design site (#2 blend)')
  assert.match(s.status, /GOV-DS-2026-02/, 'status names the design system')
  assert.match(s.components, /CitationChip/, 'component table lists a real ai component')
  assert.match(s.imports, /@risqbase-inc\/ui-components\/ai/, 'imports show the ai subpath')
  assert.doesNotMatch(s.components, /reserved for later sprints/i, 'no stale "reserved" prose')
})

test('inject() fills every marker and is idempotent', () => {
  const { current, next } = generate()
  // Every AUTOGEN block must have been resolved (no leftover placeholder text).
  assert.doesNotMatch(next, /_\(generated by `npm run readme:build`/, 'placeholders are replaced')
  // Idempotency: regenerating from the just-generated README yields no change —
  // this is exactly what `readme:check` relies on.
  const again = inject(next, renderSections(collect()))
  assert.equal(again, next, 'second injection is a no-op')
  // Sanity: injection actually changed the stale on-disk file at least once
  // in a fresh tree (current still has placeholders before first build).
  assert.equal(typeof current, 'string')
})

test('inject() throws when a marker pair is missing', () => {
  assert.throws(
    () => inject('# readme with no markers', renderSections(collect())),
    /missing the AUTOGEN markers/,
  )
})
