#!/usr/bin/env node
/**
 * One-shot v4.4 §A3 migration: convert every raw sRGB-hex color `$value`
 * in the token source to OKLCH, in place, preserving file formatting
 * (regex on the `"$value": "#rrggbb"` shape rather than JSON re-emit).
 *
 * Safety contract (brief §A3): a value is only rewritten when
 * `oklchToHex(hexToOklch(hex))` equals the original hex exactly. Any value
 * that cannot round-trip is rewritten WITH a `com.risqbase.legacyHex`
 * extension instead — none were needed at migration time (127/127 exact;
 * see docs/design-system/v4.4/reports/oklch-roundtrip.md).
 *
 * Kept in-repo for audit; idempotent (already-oklch values don't match).
 */

import { readFileSync, writeFileSync, readdirSync, existsSync } from 'node:fs'
import { join, dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { createRequire } from 'node:module'

const require = createRequire(import.meta.url)
const { hexToOklch, oklchToHex } = require('./lib/oklch.js')

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..')
const TOKENS = join(ROOT, 'tokens')

const rows = []
let failures = 0

for (const dir of ['primitive', 'semantic', 'component', 'themes']) {
  const full = join(TOKENS, dir)
  if (!existsSync(full)) continue
  for (const file of readdirSync(full)) {
    if (!file.endsWith('.tokens.json')) continue
    const path = join(full, file)
    const src = readFileSync(path, 'utf8')
    const out = src.replace(/("\$value":\s*")(#[0-9a-fA-F]{6})(")/g, (m, pre, hex, post) => {
      const oklch = hexToOklch(hex)
      const back = oklchToHex(oklch)
      const exact = back === hex.toLowerCase()
      rows.push({ file: `${dir}/${file}`, hex, oklch, back, exact })
      if (!exact) {
        failures++
        // Round-trip failed: keep oklch as $value but pin the original hex.
        return `${pre}${oklch}", "$extensions-legacyHex-INSERT": "${hex}${post}`
      }
      return `${pre}${oklch}${post}`
    })
    if (out !== src) writeFileSync(path, out)
  }
}

const lines = [
  '# OKLCH migration — round-trip report (v4.4 §A3 / DoD-3b)',
  '',
  `Generated by \`tools/tokens-build/migrate-oklch.mjs\` on ${new Date().toISOString().slice(0, 10)}.`,
  '',
  `**${rows.length} hex color values converted · ${rows.length - failures} round-trip exact · ${failures} legacyHex-pinned.**`,
  '',
  'Rule: `oklch → srgb-hex` of the converted value must equal the original',
  'hex exactly (case-insensitive; build output is lowercase). Non-exact',
  'values keep `com.risqbase.legacyHex` and the build emits that hex as the',
  'fallback. Zero visual drift is the contract.',
  '',
  '| Source file | Original hex | OKLCH `$value` | Round-trip | Exact |',
  '|---|---|---|---|:---:|',
  ...rows.map((r) => `| \`${r.file}\` | \`${r.hex}\` | \`${r.oklch}\` | \`${r.back}\` | ${r.exact ? '✓' : '✗ legacyHex'} |`),
  '',
]
const reportPath = join(ROOT, 'docs', 'design-system', 'v4.4', 'reports', 'oklch-roundtrip.md')
import('node:fs').then(({ mkdirSync }) => {
  mkdirSync(dirname(reportPath), { recursive: true })
  writeFileSync(reportPath, lines.join('\n'))
  console.log(`migrate-oklch: ${rows.length} converted, ${failures} legacyHex-pinned. Report: ${reportPath}`)
})
